
cursor_trail 1
font_size 10.0
font_family BigBlueTermPlusNerdFontMono
background_opacity 0
confirm_os_window_close 0
dynamic_background_opacity yes
foreground                #f20000

selection_background      #000000
selection_foreground      #f20000

url_color                 #f20000

wayland_titlebar_color    system
macos_titlebar_color      system

cursor                    #f20000
cursor_text_color         #000000

active_border_color       #1e1e1e
inactive_border_color     #282828
bell_border_color         #ed333b
visual_bell_color         none

active_tab_background     #000000
active_tab_foreground     #f20000
inactive_tab_background   #1c1c1c
inactive_tab_foreground   #b0afac
tab_bar_background        none
tab_bar_margin_color      none

color2  #f20000
