animations {
    enabled = false
}

# BACKGROUND
background {
    monitor =
    path = ~/Pictures/best.png
    #color = 
    blur_passes = 0
    contrast = 1
    brightness = 0.5
    vibrancy = 0.2
    vibrancy_darkness = 0.2
    xray = true 
}

# GENERAL
general {
    no_fade_in = true
    no_fade_out = true
    hide_cursor = false
    grace = 0
    disable_loading_bar = true
}

# INPUT FIELD
input-field {
    monitor =
    size = 300, 300
    hide_curor = true
    outline_thickness = 5
    dots_size = 0.1 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(242, 0, 0, 0)
    fail_color = rgba(242,0,0,1)
    font_color = rgba(f2000000)
    fade_on_empty = true
    dots_text_format = *
    fail_text = 
    rounding = -1
    check_color = rgba(204, 136, 34, 0)
    placeholder_text = Please Authenticate
    hide_input = true
    position = 0, 15
    halign = center
    valign = center
}
